FROM node:15.13.0-alpine


ENV PORT=5000
ENV DBNAME=e2e
ENV NODE_ENV=development


RUN mkdir -p /app
WORKDIR "/app"


COPY package*.json ./



RUN npm config set unsafe-perm true
# we use npm ci here so only the package-lock.json file is used
RUN npm config list \
    && npm ci \
    && npm cache clean --force


COPY . .
EXPOSE 5000

CMD ["npm", "run", "dev"]














