
version: '3.4'
services:

  # nginx:
  #   image: 'nginx:stable-alpine'
  #   ports: 
  #     - 80:80
  #     - 443:443
  #   tty: true
  #   depends_on: 
  #     # - sql
  #     # - api
  #     # - web
  #   volumes: 
  #     # remember!!!!!!! add trust proxy to nodejs services
  #     - ../../app/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro #read only 

  sql:
    image: mysql
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
        reservations:
          cpus: '1'
          memory: '512M'

  api:
    build: 
      context: ../../app/api
    restart: always
    depends_on:
      - sql
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'
        reservations:
          cpus: '1'
          memory: '512M'

  web: 
    build:
      context: ../../app/web
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
        reservations:
          cpus: '1'
          memory: '512M'
    depends_on: 
      - api
      - sql
    tty: true

volumes:
  sqlvol:
    driver: local