version: '3.4'
services:

  # nginx:
  #   stdin_open: true

  sql:
    stdin_open: true
    # command: --init-file ../../app/mysql-init/init.sql
    # entrypoint: # create db if not exist
    #     sh -c "
    #       echo ../../app/mysql-init/init.sql > /docker-entrypoint-initdb.d/init.sql;
    #       /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8 --collation-server=utf8_general_ci " 
    volumes: 
      - ../../app/mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - sqlvol:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: e2ecubbit
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    ports:
      - 3306:3306

  # api:
  #   build: 
  #     dockerfile: Dockerfile.dev
  #   stdin_open: true
  #   volumes: 
  #     - /app/node_modules 
  #     - ../../app/api:/app
  #   # command: sh -c "/wait && npm run dev"
  #   environment:
  #     - WAIT_HOSTS=sql:3306
  #     - WAIT_HOSTS_TIMEOUT=300
  #     - WAIT_SLEEP_INTERVAL=30
  #     - WAIT_HOST_CONNECT_TIMEOUT=30
  #     - PORT=5000
  #     - DBURL=mysql://<DBUSER>:<DBPASS>@<DBSERVICE>/<DBNAME>
  #     - DBSERVICE=sql
  #     - DBPASS=password
  #     - DBUSER=user
  #     - DBNAME=e2ecubbit
  #   ports:
  #     - 5000:5000
      
  # web: 
  #   build:
  #     dockerfile: Dockerfile.dev
  #   stdin_open: true
  #   volumes: 
  #     - /app/node_modules
  #     - ../../app/web:/app
  #   environment: 
  #     - API=http://api:5000
  #     - NODE_ENV=development
  #   ports: 
  #     - 3000:3000