export enum E2EActionEnum {
  ADD_KEY = 'ADD_KEY',
  LOADING = 'LOADING',
  FILE_META = 'FILEMETA',
  CLEARSTORE = 'CLEARSTORE',
  SEND_HASHED = 'SEND_HASHED',
  VERIFYENCRYPTION = 'VERIFYENCRYPTION'
}
